name: Backup Test

on:
  schedule:
    # - cron: "0 0 * * 0"  # Runs every Sunday at midnight; adjust as needed
    - cron: "0 0 1 * *"  # Runs on the first day of every month at midnight; adjust as needed
  push:
    branches:
      - main
    paths:
      - .github/workflows/backup-test.yml
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: backup-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Rclone
        uses: BenjiThatFoxGuy/setup-tclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG_B64 }}
      - name: Sync IA via rclone
        run: |
          rclone sync teldrive-cloud:Downloads/e621/zazush-una ia2:e621_zazush-una --retries 10 --max-duration 10m --max-transfer 10M --low-level-retries 3 --internetarchive-wait-archive 30s --track-renames --check-first --checkers 10 --transfers 10 --metadata --cutoff-mode soft --metadata-exclude \"source=metadata\" --metadata-exclude \"format=Metadata\" --check-first --exclude=\"__ia_thumb.jpg\" --exclude=\"___ia_thumb.jpg\" --tpslimit=0.9 --tpslimit-burst=3 --timeout=1h
      - name: Dispatch Cleanup
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: BenjiThatFoxGuy/actions
          event-type: cleanup

  sync2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Rclone
        uses: BenjiThatFoxGuy/setup-tclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG_B64 }}
      - name: Sync iCloud via rclone
        run: |
          rclone sync icloud:/Substance teldrive-cloud:/Substance --retries 10 --max-duration 10m --max-transfer 1G --low-level-retries 3 --track-renames --check-first --checkers 10 --transfers 4 --metadata --cutoff-mode soft --metadata-exclude \"source=metadata\" --metadata-exclude \"format=Metadata\" --check-first --exclude=\"__ia_thumb.jpg\" --exclude=\"___ia_thumb.jpg\" --timeout=1h
      - name: Dispatch Cleanup
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: BenjiThatFoxGuy/actions
          event-type: cleanup

  trigger-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dispatch Cleanup
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: BenjiThatFoxGuy/actions
          event-type: cleanup

  trigger-cleanup1:
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dispatch Cleanup
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: BenjiThatFoxGuy/actions
          event-type: cleanup


  trigger-cleanup2:
    runs-on: ubuntu-latest
    needs: sync2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dispatch Cleanup
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: BenjiThatFoxGuy/actions
          event-type: cleanup
